services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin-php
    volumes:
      - .:/var/www/html
    networks:
      - admin-net

  caddy:
    image: caddy:2-alpine
    container_name: admin-caddy
    ports:
      - "8080:80" # Change later for Traefik
    volumes:
      - .:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - php
    networks:
      - admin-net

networks:
  admin-net:
    driver: bridge
